CREATE OR REPLACE FUNCTION         "F_APP_PREF" (p_chave IN VARCHAR2) RETURN VARCHAR2 IS
  v_valor VARCHAR2(4000);
BEGIN
  SELECT valor INTO v_valor FROM CFG_APP_PREFERENCIAS WHERE chave = p_chave;
  RETURN v_valor;
EXCEPTION
  WHEN NO_DATA_FOUND THEN RETURN NULL;
END;
/
