CREATE OR REPLACE FUNCTION       f_parse_data(p_str IN VARCHAR2) RETURN DATE DETERMINISTIC IS
BEGIN
  IF p_str IS NULL THEN RETURN NULL; END IF;
  RETURN COALESCE(
    TO_DATE(p_str DEFAULT NULL ON CONVERSION ERROR, 'DD/MM/YYYY'),
    TO_DATE(p_str DEFAULT NULL ON CONVERSION ERROR, 'YYYY-MM-DD'),
    TO_DATE(p_str DEFAULT NULL ON CONVERSION ERROR, 'YYYYMMDDHH24MISS'));
END;
/
